id: mydrg
canonical: https://vivekjason.github.io/drg-fhirIG
name: moh.my.drg
title: "Malaysia DRG (MY-DRG) Implementation Guide (R4)"
status: draft
version: 0.1.1
fhirVersion: 4.0.1
releaseLabel: ci-build
copyrightYear: 2025
license: CC-BY-NC-4.0

publisher:
  name: "MOH Malaysia – Digital Health Division"
  url: "https://www.moh.gov.my"

# Keep dependencies simple for R4
dependencies:
  hl7.terminology: 5.5.0
  # If you later need general R4 extensions, uncomment:
  # hl7.fhir.uv.extensions.r4: 5.2.0

menu:
  Home: index.html
  Artifacts: artifacts.html
