name: Build & Publish MY-DRG IG (R4)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build IG with Publisher
        uses: qligier/fhir-ig-action@v0.3.0
        with:
          sushi: true
          publisher_version: latest

      - name: Install WeasyPrint
        run: |
          python3 -m pip install --upgrade pip
          pip install weasyprint
      - name: Render PDF
        run: |
          mkdir -p output/downloads
          weasyprint output/index.html output/downloads/MYDRG-IG.pdf

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output